### ISSUE TITLE
Support assert

### ISSUE THREAD

**Issue by danmichaelo** [mwclient/mwclient#125]
[API:Assert](https://www.mediawiki.org/wiki/API:Assert)

Could it be a good idea to add `assert=user` by default to `Page.save()` ?

**Comment by scholer** [comment]
Sounds like a good idea! My reading is that ```assert=user``` enables better error messages (```assertuserfailed```) and provides few drawbacks otherwise. 

How do you want to handle the error? Should we create a new exception class in mwclient.errors, e.g. ```AssertUserFailedError```, and raise that error in ```Site.handle_api_result()```? Or just raise ```APIError``` and either deal with it in ```Page.handle_edit_error()```, or in the ```except mwclient.errors.APIError as e:``` block of ```Page.save()``` -- or not deal with it at all and just continue to raise an APIError.

Could there be an issue if a client implementation relies on catching the current errors and that somehow fails if a new ```assertuserfailed``` error is raised? I would assume that if we just make ```AssertUserFailedError``` a subclass of ```EditError``` or ```APIError```, then that should be compatible with how current client implementations handles errors. But I could be wrong.. 

The use case seems pretty solid; if AssertUserFailedError is raised, then inform the user that s/he has been logged out and take action to log in again.

**Comment by danmichaelo** [comment]
When I looked at the code, I was reminded that we already have trigger `LoginError` if `Site.force_login is True and Site.loggedin is False`, so it seems to make sense to me to only send `assert=user` if ``Site.force_login is True` and to trigger the same exception. Since I find the name LoginError a bit confusing I created a new subclass of it. It's perhaps not ideal that the exception is not a subclass of `APIError`, but we already have a similar case for `PageProtectedError`, which cannot be a subclass of `APIError` because it can also be thrown before the actual api call is made (if we don't have the "edit" right).

I'll leave this branch open a few days before merging in case you have comments.

**Comment by scholer** [comment]
OK, that makes sense. :)

What happens if a user login expires during a session? Would that be a use case?

Also, is there any downsides (e.g. performance) in sending ```assert=user```? That is, do requests take longer when a user is already properly logged in? Otherwise we could just always send it but continue to raise the existing set of errors.

FYI, our wiki instance is using OAuth (Google) for auth, and we are just grabbing the session id cookie and passing that in the headers for login (we do not send user name or password). When a session id expired (about every second week), the API requests fail with ```HTTPRedirectError```. Crude, but it works very well for our typical workflow.

**Comment by danmichaelo** [comment]
@scholer 

> What happens if a user login expires during a session? Would that be a use case?

Then a `LoginError` will be thrown.

> Also, is there any downsides (e.g. performance) in sending ```assert=user```? That is, do requests take longer when a user is already properly logged in? Otherwise we could just always send it but continue to raise the existing set of errors.

I'm not aware of any downsides. With "always", do you mean that we should also send it on read-operations, not just with `action=edit`?

> FYI, our wiki instance is using OAuth (Google) for auth, and we are just grabbing the session id cookie and passing that in the headers for login (we do not send user name or password). When a session id expired (about every second week), the API requests fail with ```HTTPRedirectError```. Crude, but it works very well for our typical workflow.

Interesting. Does it only fail on `action=edit` , or also on other requests? 

(On the side, can you use the new OAuth implementation (#115), or do you need an interactive flow, redirecting the user to a browser and such?)

**Comment by scholer** [comment]
> With "always", do you mean that we should also send it on read-operations, not just with action=edit?

Uh, I hadn't considered that, but maybe(?). But I guess it is only relevant if (a) it does not have any adverse effects on performance, and (b) it is relevant for e.g. better error handling. I'm not sure I'd be the best to give advice on this issue, given our peculiar login flow ;)

> Does it only fail on action=edit , or also on other requests?

When the session id has expired, all requests fail. The API request is just, literally, forwarded to the login page. Not sure whether that is intended behaviour or just how our service provider happens to have configured the mediawiki instance.

> can you use the new OAuth implementation (#115), or do you need an interactive flow, redirecting the user to a browser and such?

Our Mediawiki instance uses Google to authenticate. Google's OAuth seems rather involved (e.g. [OAuth2InstalledApp](https://developers.google.com/identity/protocols/OAuth2InstalledApp) and [OAuth2ForDevices](https://developers.google.com/identity/protocols/OAuth2ForDevices)) and most of the docs are described from what would be the mediawiki-instance's point of view, not "our app, which interacts with mediawiki-server, which auths using Google OAuth"... I'm sure it could be done, but it seemed a little elaborate... On the other hand, all our users are already logged in with their Chrome browser. Hijacking the session ID from Chrome's cookie database was fairly easy and can be done without any interaction from the user. 

Auth is essentially like this: (1) Try to interact with the mediawiki server. (2) Fail? Extract session ID from Chrome's cookie database. If session ID differ from the previous one, then try this new session ID. (3) If that fails, open the wiki login page. Since users are almost always correctly logged in with their Chrome browser, they are in effect also always authenticated when using our app. This is arguably not "the right way" to do auth, but it works really well and it was super easy to implement. :D

**Comment by danmichaelo** [comment]
Closing this for now
