### ISSUE TITLE
Be consistent in args vs kwargs

### ISSUE THREAD

**Issue by lukasjuhrich** [mwclient/mwclient#128]
Glancing over the source, I often find `kwargs.update(args)`. Also, in `Listing.__init__` of `listing.py`:

``` python
        data = self.site.api(
            'query', (self.generator, self.list_name),
            *[(text_type(k), v) for k, v in six.iteritems(self.args)]
        )
```

What reason is there for this duality of 2-tuples as arguments vs keyword arguments? Why not just consistently use keyword arguments?

If there is a reason for it, documenting it might be appropriate.

**Comment by marcfrederick** [comment]
The is necessary, because MediaWiki uses some parameter names (e.g., `continue`, `from`) that conflict with Python's reserved keywords, making them unusable as keyword arguments in Python. For example, the following code:

```python
site.raw_api('query', continue='1234567')
```

Will lead to this `SyntaxError`:

```
File ".../scratch.py", line 8
  site.raw_api('query', continue='1234567')
                        ^^^^^^^^
SyntaxError: invalid syntax
```

To avoid this conflict, these arguments can be passed as tuples in `*args` instead:

```python
site.raw_api('query', ('continue', '1234567'))
```

For a practical example where this workaround is required, see [this line in page.py](https://github.com/mwclient/mwclient/blob/25d0a923d487758ad401be5f5bca1f00419a394f/mwclient/page.py#L394-L395). PR #372 adds this info to some of the relevant functions docstrings.

**Comment by lukasjuhrich** [comment]
> The is necessary, because MediaWiki uses some parameter names (e.g., continue, from) that conflict with Python's reserved keywords, making them unusable as keyword arguments in Python. 

But shouldn't dict unpacking work in this case?

```python
site.raw_api("query", **{"continue": "1234567"})
```

Another alternative would be to use an underscore-trimming convention, akin to the way wtforms [allows one to specify `class_` to set a html `class="…"` attribute](https://github.com/pallets-eco/wtforms/blob/3ba396e769e9ab58888a8cae940f4211d3f31fee/src/wtforms/widgets/core.py#L33-L37)
