### ISSUE TITLE
Fetching Special pages doesn't work.

### ISSUE THREAD

**Issue by roysmith** [mwclient/mwclient#193]
Running this code:

```
import mwclient
site = mwclient.Site('en.wikipedia.org')
page = site.Pages['Special:RandomInCategory/Pending_AfC_submissions']
print(page)
print(repr(page.text()))
```
prints:

```
<Page object 'b'Special:RandomInCategory/Pending AfC submissions'' for <Site object 'en.wikipedia.org/w/'>>
''
```
I expected it would actually fetch a random page in that category, just like entering 'Special:RandomInCategory/Pending AfC submissions' into a search box on the web does.

**Comment by danmichaelo** [comment]
Nah, special pages are not supported. For some of them, there are special api endpoints, but not for this one.

Luckily, it's quite easy to implement this functionality yourself:

```python
import random
from mwclient import Site
site = Site('en.wikipedia.org')
cat = site.categories['Pending AfC submissions']
pages = list(cat.members(namespace='0|118'))  # choose namespaces to your liking
randompage = pages[random.randint(0, len(pages))]
```

Note that while testing this with `namespace=0` I ran into a new bug (#194). This has been fixed in version 0.9.1 that was just released, so I recommend upgrading to that.
