### ISSUE TITLE
Remove dependency on mock

### ISSUE THREAD

**Issue by mcepl** [mwclient/mwclient#276]
Could you please consider to use this [patch](https://github.com/mwclient/mwclient/files/9033723/demock.patch.txt) to remove the dependency on the external mock. It is unnecessary since at least Python 3.3, when it was included in the `unittest` module of the standard library.

(sorry, I won't create new pull request; I am a maintainer of approx. 2000 Python packages in openSUSE, I cannot fork all of them)

**Comment by marcfrederick** [comment]
Hey @mcepl, sorry it took so long to get back to you on this. This project is currently still supporting Python 2.7, making the `mock` package necessary for now. However, the `setup.py` seems to have changed since you created the path. In the current version, the dependency is only required for pre-3.3 versions of Python:

https://github.com/mwclient/mwclient/blob/master/setup.py#L36

**Comment by AdamWill** [comment]
This was resolved by https://github.com/mwclient/mwclient/pull/310 , I believe. (also hey @mcepl ! long time no see :>)
