### ISSUE TITLE
Fix pypi.org Project links > Homepage

### ISSUE THREAD

**Issue by mikez** [mwclient/mwclient#277]
Currently, on https://pypi.org/project/mwclient/, the "Homepage" link on the left points to https://github.com/btongminh/mwclient

Thus, all Github stats and links are incorrect.

**Comment by marcfrederick** [comment]
Thank you for bringing this to our attention. I noticed that the issue you reported was addressed in pull request #269. However, it appears that the fix has yet to be implemented in PyPI, as there have been no new releases since, due to a lack of active maintainers.

We are currently working on reviving the project (#280) - with any luck, we'll soon be in a position to release an updated version that includes the necessary changes to resolve this issue. Thank you for your patience and understanding.

**Comment by mikez** [comment]
@marcfrederick Thank you for the pointers.

**Comment by AdamWill** [comment]
we finally have access to pypi, so I'm working on putting together the bits for a new release. when we do that the homepage will be corrected (finally).

**Comment by WolfgangFahl** [comment]
can we get this done at MediaWiki Hackathon in Tallinn?

**Comment by AdamWill** [comment]
see other thread.

**Comment by marcfrederick** [comment]
This is fixed as of v0.11.0 🚀
