### ISSUE TITLE
Is there a limit of 3 page reads when using mwclient or Wikipedia... Error at opening 4'th page from python program

### ISSUE THREAD

**Issue by kantheerava** [mwclient/mwclient#300]
?

I am trying to add category to Wikipedia pages.

I can open and read texts in first 3 Wikipedia pages, with a delay of 40 seconds.
When I open 4'th web page
I get below Error:

`
 raise errors.APIError(info['error']['code'],
mwclient.errors.APIError: ('abusefilter-warning', , 'See https://en.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes.') 
`

My Code:

`
#target_pages has titles of 10 Wikipedia pages

for each in target_pages:
sleep(40)
page = site.pages[each]
  text = page.text()
  if ('[[c_movie_category]]' in text) :
    pass
  else:
    text = text+c_movie_category 
    result = page.save(text, comment)
`

**Comment by AdamWill** [comment]
btw, your code also looks a bit odd to me. Is `c_movie_category` a variable or a string? Because you seem to be using the literal string `c_movie_category` in the line `if ('[[c_movie_category]]' in text) :`, but a variable named `c_movie_category` in the line `text = text+c_movie_category`.

Assuming it's meant to be a variable, the first line should be something like `if f'[[{c_movie_category}]]' in text:`

**Comment by kantheerava** [comment]
Thank you @AdamWill for your inputs.
After working with the Admin, I found the reason for hitting the abuse filter.
It was a configuration on the local wikipedia

Your Inputs helped to fix this Issue.

Thanks again.
