### ISSUE TITLE
Update Page state on save()

### ISSUE THREAD

**Issue by danmichaelo** [mwclient/mwclient#63]
I find the following counter-intuitive:

```
> page = site.pages['Some new page']
> page.save('Some text')
> page.exists
False
> page.text()
''
> page.touched()
 (0, 0, 0, 0, 0, 0, 0, 0)
```

and so on.. After a save, the page does not reflect the updated state of the page. This could be solved by making extra API call to update page properties after save. For users trying to minimize the number of API calls, there should possibly be an option to disable this update..

**Comment by msj2** [comment]
I too am finding same Error.

page.text() gives the text from Wiki page
I update the text & call page.save with 2 params (text, 'summary text')
page.save won't save
'On wikipedia, history won't even show the edit.

page.save returns.. 

{u'nochange': u'', u'contentmodel': u'wikitext', u'pageid': XXXX, u'result': u'Success', u'title':....)...
}

nochange ..implies changes weren't made???

**Comment by danmichaelo** [comment]
Your problem is a different one. The API response says that you send back the original text, not the modified text. Without more code I cannot say anything more.

**Comment by azurstarshine** [comment]
Essentially, this is cache invalidation problem. A save should invalidate the cache, so the simplest fix would be to just *discard* all the state on `save`. Then when the user invokes a function to obtain state, it forces the object (cache) to update. This would also avoid the overhead of making unnecessary requests, since they would only be made when the user attempts to access the data. It would not incur more overhead than fully updating the object, either.
