### ISSUE TITLE
'New messages' flag doesn't work

### ISSUE THREAD

**Issue by Pathoschild** [mwclient/mwclient#90]
`Site.hasmsg` is set when userinfo has a `message` field (see [client.py#L221](https://github.com/mwclient/mwclient/blob/67a3bad88824f4fd75a6136b72d7fce518b1df5a/mwclient/client.py#L221)), but the actual property returned is `messages`:

```json
{
    "batchcomplete": "",
    "query": {
        "userinfo": {
            "id": 15486,
            "name": "Pathoschild",
            "messages": ""
        }
    }
}
```

At least as of [1.26wmf12](https://meta.wikimedia.org/wiki/Special:Version). I'm not sure if the field was renamed recently, but I don't see anything in the MediaWiki release notes for [1.25](https://www.mediawiki.org/wiki/MediaWiki_1.25) or [1.26](https://www.mediawiki.org/wiki/MediaWiki_1.26).

**Comment by danmichaelo** [comment]
Seems like it has been "messages" all the way since [the beginning](https://git.wikimedia.org/blob/mediawiki%2Fcore.git/c4aad95b10ed877e4a8c4f1b0cf9a1f1ee77edf2/includes%2Fapi%2FApiQueryUserInfo.php), but that the documentation (now in [MediaWiki:Apihelp-query+userinfo-param-prop](https://translatewiki.net/wiki/MediaWiki:Apihelp-query%2Buserinfo-param-prop)) has also been wrong all the time :)

**Comment by danmichaelo** [comment]
Thanks for spotting this. I reported the documentation issue at https://phabricator.wikimedia.org/T105120

Wonder if it would make more sense to have this as a method, so you can always have the live value, but I guess that also goes for other `userinfo` props.
